// Generated by CoffeeScript 1.8.0
var TestSuite;

TestSuite = (function() {
  TestSuite.prototype.TESTS = ['randomDataTest'];

  TestSuite.prototype.FIELDS = ['country', 'currency', 'input', 'include_commission', 'rate', 'expected_amount', 'actual_amount', 'expected_fees', 'actual_fees', 'expected_total', 'actual_total', 'expected_receives', 'actual_receives', 'pass'];

  function TestSuite(ele) {
    var field, _i, _len, _ref;
    window.frames[0].converter.CONFIGURATION.conversion_keypress_delay = 0;
    $('#test-results thead').append('<tr></tr>');
    _ref = this.FIELDS;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      field = _ref[_i];
      $('#test-results thead tr').append("<th>" + (field.replace(/_/g, ' ')) + "</th>");
    }
    this.listen();
    this.runTests();
  }

  TestSuite.prototype.listen = function() {
    $(window.frames[0].document).find('#converter #include-commission').on('change', (function(_this) {
      return function(e) {
        return window.frames[0].converter.checkboxHandler($(window.frames[0].document).find('#converter #include-commission').is(":checked"));
      };
    })(this));
    $(window.frames[0].document).find('#converter .select select').on('change', (function(_this) {
      return function(e) {
        return window.frames[0].converter.selectHandler($(e.target).parents('div').attr('id'), $(e.target).val());
      };
    })(this));
    $(window.frames[0].document).find('#converter #input').on('keyup', (function(_this) {
      return function(e) {
        return window.frames[0].converter.inputHandler(e.target.value);
      };
    })(this));
    $(window.frames[0].document).find('#converter .select select').change();
    $(window.frames[0]).blur((function(_this) {
      return function() {
        window.clearInterval(window.currency_interval);
        window.currency_interval = null;
        window.clearTimeout(window.currency_timeout);
        return window.currency_timeout = null;
      };
    })(this));
    $(window.frames[0]).focus((function(_this) {
      return function() {
        if (!window.currency_interval) {
          return _this.runTests();
        }
      };
    })(this));
    return $(window.top).focus((function(_this) {
      return function() {
        if (!window.currency_interval) {
          return _this.runTests();
        }
      };
    })(this));
  };

  TestSuite.prototype.runTests = function() {
    var test, _i, _len, _ref, _results;
    if (JSON.stringify(window.frames[0].converter.rates) === '{"AUD":1}') {
      return window.setTimeout(((function(_this) {
        return function() {
          return _this.runTests();
        };
      })(this)), 100);
    } else {
      _ref = this.TESTS;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        test = _ref[_i];
        _results.push(this[test]());
      }
      return _results;
    }
  };

  TestSuite.prototype.roundNum = function(number, significant_digits) {
    var rounder;
    if (significant_digits == null) {
      significant_digits = window.frames[0].converter.CONFIGURATION.significant_digits;
    }
    number = parseFloat(number.toString().replace(',', ''));
    rounder = Math.pow(10, significant_digits);
    return (Math.round(number * rounder) / rounder).toFixed(significant_digits);
  };

  TestSuite.prototype.parseNum = function(input) {
    if (!input || !input.toString().replace(/,|\./g, '').match(/[0-9]/)) {
      return '';
    }
    return parseFloat(parseFloat(input.toString().replace(/,/g, '')).toFixed(window.frames[0].converter.CONFIGURATION.significant_digits));
  };

  TestSuite.prototype.getCommission = function(amount) {
    amount = this.parseNum(amount);
    this.commission_rate = 0.05;
    if (amount >= 1000) {
      this.commission_rate = 0.04;
    }
    if (amount >= 3000) {
      this.commission_rate = 0.03;
    }
    if (amount >= 4000) {
      this.commission_rate = 0.02;
    }
    if (amount >= 5000) {
      this.commission_rate = 0.02;
    }
    return amount * this.commission_rate;
  };

  TestSuite.prototype.randomDataTest = function() {
    this.currencies = window.frames[0].converter.CONFIGURATION.currencies_enabled_remote;
    $(window.frames[0].document).find('#converter .select select').change();
    window.clearInterval(window.currency_interval);
    window.currency_interval = window.setInterval(((function(_this) {
      return function() {
        return _this.inputData(1);
      };
    })(this)), 100);
    window.clearTimeout(window.currency_timeout);
    return window.currency_timeout = window.setTimeout("window.clearInterval(window.currency_interval)", 5 * 60 * 1000);
  };

  TestSuite.prototype.inputData = function(n) {
    $(window.frames[0].document).find('#include-commission').prop('checked', Math.random() > 0.6).change();
    $(window.frames[0].document).find('#remote-country select').val(this.currencies[Math.floor(Math.random() * this.currencies.length)]).change();
    $(window.frames[0].document).find('#currency select option').eq(~~(Math.random() * $(window.frames[0].document).find('#currency select option').length)).prop('selected', true).change();
    $(window.frames[0].document).find('#input').val(this.roundNum(Math.random() * 10000)).keyup();
    return window.setTimeout(((function(_this) {
      return function() {
        return _this.checkResult(n);
      };
    })(this)), 10);
  };

  TestSuite.prototype.checkResult = function(n) {
    var col, tr, value, _i, _len, _ref;
    this.country = $(window.frames[0].document).find('#remote-country select').val();
    this.currency = $(window.frames[0].document).find('#currency select option:selected').val();
    this.include_commission = $(window.frames[0].document).find('#include-commission').prop('checked');
    this.input = $(window.frames[0].document).find('#input').val();
    this.actual_amount = $(window.frames[0].document).find('#amount').text().replace(/,/, '');
    this.actual_fees = $(window.frames[0].document).find('.fees > .amount').text().replace(/,/, '');
    this.actual_total = $(window.frames[0].document).find('#total-due').text().replace(/,/, '');
    this.actual_receives = $(window.frames[0].document).find('.receives .amount').text().replace(/,/, '');
    this.remote_currency = window.frames[0].converter.remote_currency;
    this.rates = window.frames[0].converter.rates;
    this.rate = this.rates[this.remote_currency];
    if (this.currency === 'AUD') {
      this.local_value = this.parseNum(this.input);
      this.commission = this.getCommission(this.local_value);
      if (this.include_commission) {
        this.local_value -= this.commission;
      }
      this.remote_value = this.local_value / this.rates[this.remote_currency];
    } else if (this.currency === this.remote_currency) {
      this.remote_value = this.input;
      this.commission = this.getCommission(this.remote_value * this.rates[this.remote_currency]);
      this.local_value = this.remote_value * this.rates[this.remote_currency];
    } else {
      this.local_value = this.input * this.rates[this.currency];
      this.commission = this.getCommission(this.local_value);
      if (this.include_commission) {
        this.local_value -= this.commission;
      }
      this.remote_value = this.local_value / this.rates[this.remote_currency];
    }
    this.expected_amount = this.roundNum(this.local_value);
    this.expected_fees = this.roundNum(this.commission);
    this.expected_total = this.roundNum(this.local_value + this.commission);
    this.expected_receives = this.roundNum(this.remote_value);
    this.pass = true;
    if (this.expected_amount !== this.actual_amount) {
      this.pass = false;
    }
    if (this.expected_fees !== this.actual_fees) {
      this.pass = false;
    }
    if (this.expected_total !== this.actual_total) {
      this.pass = false;
    }
    if (this.expected_receives !== this.actual_receives) {
      this.pass = false;
    }
    if (!(this.pass || n > 8)) {
      return window.setTimeout(((function(_this) {
        return function() {
          return _this.checkResult(n + 1);
        };
      })(this)), 10);
    }
    tr = $('<tr></tr>');
    _ref = this.FIELDS;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      col = _ref[_i];
      value = this[col];
      if (value && value.toString().match(/\d+/) && col !== 'rate' && col !== 'include_commission') {
        value = this.roundNum(value);
      }
      if (col === 'pass') {
        if (this.pass) {
          value = '✓';
        }
        if (!this.pass) {
          value = '✗';
        }
      }
      tr.append("<td class='" + col + "' title='" + (col.replace(/_/g, ' ')) + "'>" + value + "</td>");
    }
    if (this.pass === false) {
      tr.addClass('fail');
    }
    if (this.pass === true) {
      tr.addClass('pass');
    }
    if (this.input) {
      return $('#test-results').append(tr);
    }
  };

  return TestSuite;

})();
